version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    assignees:
      - 'nothub'
    reviewers:
      - 'nothub'
    commit-message:
      prefix: github-actions
      include: scope
